package lotto.error

//import lotto.policy.GamePolicy
//import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows

class ErrorHandlerTest {

	@Test
	fun `should throw RetryInputException when error is Winning NOT_IN_RANGE`() {
		assertThrows<RetryInputException> {
			ErrorHandler.check(Winning.NOT_IN_RANGE)
		}
	}

	@Test
	fun `should throw IllegalArgumentException when error is DUPLICATE_NUMBER`() {
	}

	@Test
	fun `should throw with message generated by ErrorFormatter`() {
	}
}

